# Site settings
title: Seyyed Emad Razavi | Senior Mobile Developer
email: razavioo@gmail.com
description: >-
  Senior Mobile Developer with 7+ years of experience specializing in Flutter, Kotlin, and KMP.
  Proven ability to lead cross-functional teams and implement robust architectures.
baseurl: ""
url: "https://emad.dev"
github_username:  razavioo
linkedin_username: razavioo

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - setup.sh
